---
apiVersion: v1
kind: Service
metadata:
  name: postgres
  namespace: postgres
spec:
  type: NodePort
  ports:
    - port: 5432
      nodePort: 32432
  selector:
    app: postgres
---
apiVersion: v1
kind: Secret
metadata:
  name: postgres-password
  namespace: postgres
type: Opaque
data:
  password: Z2VoZWltCg==
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
  namespace: postgres
spec:
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      securityContext:
        runAsNonRoot: true
        runAsUser: 999 # postgres
        runAsGroup: 999 # postgres
        fsGroup: 999 # postgres
      containers:
        - image: postgres:latest
          name: postgres
          env:
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-password
                  key: password
            - name: PGDATA
              value: /var/lib/postgresql/data/pgdata
          ports:
            - containerPort: 5432
              name: database
          volumeMounts:
            - name: data
              mountPath: /var/lib/postgresql/data
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: postgres
